site_name: Tiled-Land

nav:
  - Home: 'index.md'
  - Main Components:
    - Tiled Entity: 'main-entity.md'
    - Tiles and Map: 'main-map.md'
    - Agents: 'main-agent.md'
    - Rendering: 'main-rendering.md'
  - Interactive:
    - Classical GUI: 'ihm-gui.md'
    - Web App: 'ihm-web.md'
    - Multithreading: 'ihm-thread.md'
  - Geometry: 'geometry.md'

markdown_extensions:
  - attr_list
  - pymdownx.arithmatex:
      generic: true

theme:
  name: readthedocs
  collapse_navigation: True
  titles_only: True
  # include_homepage_in_sidebar: False

extra_javascript:
  - javascripts/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js

extra_css:
  - style.css
