site_name: Tiled-Land

nav:
  - Home: 'index.md'
  - Core Components:
    - Entity: 'core-entity.md'
    - Tiles and Tabletop: 'core-tabletop.md'
    - Rendering: 'core-rendering.md'
  - Agent-Based Modeling :
    - Land and Actors: 'as-land.md'
    - Agents: 'as-agent.md'
  - Interactive:
    - Classical GUI: 'ihm-gui.md'
    - Web App: 'ihm-web.md'
    - Multithreading: 'ihm-thread.md'
  - Geometry: 'geometry.md'
  - F.A.Q: 'faq.md'

markdown_extensions:
  - attr_list
  - pymdownx.arithmatex:
      generic: true

theme:
  name: readthedocs
  collapse_navigation: True
  titles_only: True
  # include_homepage_in_sidebar: False

extra_javascript:
  - javascripts/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js

extra_css:
  - style.css
